[package]
name = "read_io"
version = "0.1.1"
edition = "2021"
authors = ["Bay"]
description = "A macro to read user input easily."
repository = "https://github.com/zX3no/read_io"
readme = "README.md"
license = "MIT"


[dependencies]
